## Aporeto
[[constraint]]
  name = "github.com/aporeto-inc/bahamut"
  version = "13.x"

[[constraint]]
  name = "github.com/aporeto-inc/elemental"
  version = "3.x"

[[constraint]]
  name = "github.com/aporeto-inc/gaia"
  version = "7.x"

[prune]
  go-tests = true
  unused-packages = true
